//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseArchives
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        public Race()
        {
            this.Runners = new HashSet<Runner>();
        }
    
        public int RaceID { get; set; }
        public string City { get; set; }
        public System.DateTime DateBegin { get; set; }
        public string TypeRace { get; set; }
    
        public virtual ICollection<Runner> Runners { get; set; }
    }
}
