//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseArchives
{
    using System;
    using System.Collections.Generic;
    
    public partial class Runner
    {
        public int RunnerID { get; set; }
        public int RaceID { get; set; }
        public string RunnerName { get; set; }
        public double Odds { get; set; }
        public System.DateTime DateLatestMatches { get; set; }
        public bool Win { get; set; }
    
        public virtual Race Race { get; set; }
    }
}
